syntax = "proto3";


import "scalapb/scalapb.proto";
option (scalapb.options) = {
  // scope: FILE
  package_name: "fmgp.geo.proto.service"
  flat_package: true
  // single_file: true
  java_conversions: false
  // import: "com.thesamet.pb.MyType"
  // import: "com.thesamet.other._"
  // preamble: "sealed trait BaseMessage"
  // preamble: "sealed trait CommonMessage"
  lenses: false
  getters: false
  retain_source_code_info: false
  no_default_values_in_constructor: true //false
  // preserve_unknown_fields: false
  // enum_value_naming: CAMEL_CASE
  // enum_strip_prefix: false
  // bytes_type: "scodec.bits.ByteVector"
  scala3_sources: true
  // public_constructor_parameters: false
};

// package fmgp.geo.proto;

// The greeting service definition.
// grpcurl -plaintext localhost:9090 list fmgp.geo.proto.Visualizer
// grpcurl -plaintext localhost:9090 describe fmgp.geo.proto.Visualizer
service Visualizer {
  // grpcurl -plaintext -import-path modules/01-protos/src/main -d '{"value":"Fabio"}' -proto protobuf/geometry.proto localhost:9090 fmgp.geo.proto.Visualizer/SayHello
  rpc SayHello (DataReq) returns (DataRes) {}
  rpc SayHelloServerStreaming(DataReq) returns (stream DataRes) {}
  rpc SayHelloBidiStreaming(stream DataReq) returns (stream DataRes) {}
  rpc SayHelloClientStreaming(stream DataReq) returns (DataRes) {}
}

message DataReq {
  string value = 1;
}
message DataRes {
  string value = 1;
}
