name: CI

on:
  pull_request:
    branches-ignore:
      - "gh-pages"
  push:
    branches-ignore:
      - "gh-pages"

jobs:
  Run-Tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      # https://github.com/japgolly/setup-everything-scala
      - uses: actions/checkout@v2
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16" # or whatever
      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@v1
      - name: Cache sbt
        uses: coursier/cache-action@v6.3
      ### TESTS ###
      #- run: sbt test
      - run: sbt -mem 2048 -J-Xmx5120m threeUtils/test
      - run: sbt -mem 2048 -J-Xmx5120m modelJVM/test
      - run: sbt -mem 2048 -J-Xmx5120m modelJS/test
      # No test - run: sbt -mem 2048 -J-Xmx5120m controller/test
      # No test - run: sbt -mem 2048 -J-Xmx5120m geometryCore/test
      - run: sbt -mem 2048 -J-Xmx5120m syntaxJVM/test
      - run: sbt -mem 2048 -J-Xmx5120m syntaxJS/test
      # No test - run: sbt -mem 2048 -J-Xmx5120m prebuiltJS/test
      # No test - run: sbt -mem 2048 -J-Xmx5120m prebuiltJVM/test
      # ERROR - run: sbt -mem 2048 -J-Xmx5120m webapp/test # SyntaxError: Cannot use import statement outside a module
      # No test - run: sbt -mem 2048 -J-Xmx5120m repl/test
