name: CI

on:
  pull_request:
  push:

jobs:
  Run-Tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v12
      - uses: actions/setup-node@v2
        with:
          node-version: "16" # or whatever
      - uses: japgolly/setup-scalajs@v1
      #- run: sbt test
      - run: sbt threeUtils/test
      - run: sbt geometryModelJVM/test
      - run: sbt geometryModelJS/test
      - run: sbt geometryCore/test
      #error - run: sbt geometryWebapp/test # SyntaxError: Cannot use import statement outside a module
      - run: sbt controller/test
