name: CI
run-name: CI on ${{ github.ref_name }}

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - "gh-pages"
  push:
    branches-ignore:
      - "gh-pages"

permissions:
  contents: read

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: coursier/setup-action@v3
        with:
          jvm: temurin:21
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: npm
      - name: Cache Coursier and sbt dependencies
        uses: coursier/cache-action@v8
      - name: Install npm dependencies
        run: npm ci
      - name: Run JVM and Scala.js tests
        run: sbt -v -mem 2048 -J-Xmx5120m testAll
